# Generated by Django 4.2 on 2023-05-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mood',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='weather',
            field=models.CharField(max_length=100),
        ),
    ]
